default: &default
  adapter: mysql
  pool: 5
  timeout: 5000
  username: root
  password: root
development:
  <<: *default
  database: tic_tac_toe_development

test:
  <<: *default
  database: tic_tac_toe_test

production:
  <<: *default
  database: tic_tac_toe_production
  username: tic_tac_toe
  password: <%= ENV['TIC_TAC_TOE_DATABASE_PASSWORD'] %>
